use questiondb;
select * from question;
INSERT INTO question (topic, questiontext) VALUES 
('java', 'What is the difference between JVM stack and JVM heap?'),
('java', 'What are Java inner classes?'),
('java', 'What are anonymous classes in Java?'),
('java', 'What is the difference between static and non-static nested classes?'),
('java', 'What is Java enum?'),
('java', 'What is the use of the instanceof operator?'),
('java', 'What is the difference between final and finally in exception handling?'),
('java', 'What is the use of assert keyword in Java?'),
('java', 'What is the difference between StringBuilder and StringBuffer?'),
('java', 'What is the difference between equals() and hashCode()?'),
('java', 'What is the purpose of the Object class in Java?'),
('java', 'What is the difference between interface and functional interface?'),
('java', 'What are default and static methods in interfaces?'),
('java', 'What is the difference between early binding and late binding?'),
('java', 'What is the purpose of the transient keyword in serialization?'),
('java', 'What are Java design patterns?'),
('java', 'What is the Singleton design pattern?'),
('java', 'What is the Factory design pattern?'),
('java', 'What is the Observer design pattern?'),
('java', 'What is the difference between Comparable and Comparator?'),
('java', 'What are Java Streams?'),
('java', 'What is the difference between map() and flatMap() in streams?'),
('java', 'What are Optional objects and why are they useful?'),
('java', 'What is the difference between collect() and reduce() in streams?'),
('java', 'What is the difference between call by value and call by reference?'),
('java', 'What is the difference between synchronized method and synchronized block?'),
('java', 'What are deadlocks in Java and how can they be avoided?'),
('java', 'What is the difference between process and thread in Java?'),
('java', 'What is the difference between volatile and Atomic variables?'),
('java', 'What is the use of Java Reflection API?');

INSERT INTO question (topic, questiontext) VALUES 
('Python', 'What is Python?'),
('Python', 'Explain Python data types.'),
('Python', 'What is PEP 8?'),
('Python', 'Explain Python list comprehension.'),
('Python', 'What is a Python dictionary?'),
('Python', 'What is a Python set and how is it different from a list?'),
('Python', 'Explain Python tuples.'),
('Python', 'What is a Python function and how do you define one?'),
('Python', 'What is a Python module?'),
('Python', 'What is the difference between Python lists and arrays?'),
('Python', 'Explain Python classes and objects.'),
('Python', 'What is inheritance in Python?'),
('Python', 'What is the difference between deep copy and shallow copy in Python?'),
('Python', 'What is Python lambda function?'),
('Python', 'Explain Python decorators.'),
('Python', 'What is Python generator and yield keyword?'),
('Python', 'What is Python exception handling?'),
('Python', 'Explain Python global and local variables.'),
('Python', 'What is Python dictionary comprehension?'),
('Python', 'What is the difference between Python Python 2 and Python 3?');
